- name: Check if packages were collected successfully
  ansible.builtin.debug:
    var: ansible_facts.packages['amazon-linux-extras']

- name: Update repositories
  ansible.builtin.yum: 
    name: yum
    update_cache: yes
    state: latest

- name: Install extras
  ansible.builtin.yum:
    name: amazon-linux-extras
    update_cache: yes
    state: latest
  when: "ansible_facts.packages['amazon-linux-extras'] is undefined"

- name: Enabling php7.4
  ansible.builtin.command:
    cmd: amazon-linux-extras enable php7.4
  when: "ansible_facts.packages['amazon-linux-extras'] is undefined"

- name: Disabling php5.4
  ansible.builtin.command:
    cmd: amazon-linux-extras disable php5.4
  when: "ansible_facts.packages['amazon-linux-extras'] is undefined"

- name: Check if packages were collected successfully
  ansible.builtin.debug:
    var: ansible_facts.packages['php']

- name: Install php
  ansible.builtin.yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: [ php-cli-7.4.33, php-pdo-7.4.33, php-fpm-7.4.33, php-json-7.4.33, php-mysqlnd-7.4.33, php-7.4.33, php-gd-7.4.33 ]

- name: Changing www.conf
  ansible.builtin.copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: Changing default.conf
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: Start php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Changing rights
  ansible.builtin.file: 
    path: /usr/share/nginx/html/
    owner: nginx
    group: nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/php/handlers/main.yml