- name: Install prerequisites
  ansible.builtin.yum: 
    name: yum
    update_cache: yes
    state: latest

- name: List ansible packages
  ansible.builtin.shell:
    cmd:  'yum list install amazon-linux-extras | cut -d " " -f 1 | head -n 2'
  register: amazon_extras

- name: Install extras
  ansible.builtin.yum:
    name: amazon-linux-extras
    update_cache: yes
    state: latest
  when: "amazon_extras.stdout == 'Loaded\nAvailable'"

- name: Enabling php7.4
  ansible.builtin.command:
    cmd: amazon-linux-extras enable php7.4

- name: Disabling php5.4
  ansible.builtin.command:
    cmd: amazon-linux-extras disable php5.4

- name: List ansible packages
  ansible.builtin.shell:
    cmd: 'yum list install php | cut -d " " -f 1 | head -n 2'
  register: php

- name: Install php
  ansible.builtin.yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: [ php-cli-7.4.33, php-pdo-7.4.33, php-fpm-7.4.33, php-json-7.4.33, php-mysqlnd-7.4.33, php-7.4.33, php-gd-7.4.33 ]
  when: "php.stdout == 'Loaded\nAvailable'"

- name: Changing www.conf
  ansible.builtin.copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: Changing default.conf
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: Start php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Changing rights
  ansible.builtin.file: 
    path: /usr/share/nginx/html/
    owner: nginx
    group: nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/php/handlers/main.yml