- name: Update repositories
  ansible.builtin.dnf: 
    name: dnf
    update_cache: yes
    state: latest

# - name: Install extras
#   ansible.builtin.dnf:
#     name: amazon-linux-extras
#     update_cache: yes
#     state: latest

# - name: Enabling php7.4
#   ansible.builtin.command:
#     cmd: amazon-linux-extras enable php7.4

# - name: Disabling php5.4
#   ansible.builtin.command:
#     cmd: amazon-linux-extras disable php5.4

- name: Check if packages were collected successfully
  ansible.builtin.debug:
    var: ansible_facts.packages['php']

- name: Install php
  ansible.builtin.dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: [ php-cli, php-pdo, php-fpm, php-json, php-mysqlnd, php, php-gd ]

- name: Changing www.conf
  ansible.builtin.copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: Changing default.conf
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: Start php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Changing rights
  ansible.builtin.file: 
    path: /usr/share/nginx/html/
    owner: nginx
    group: nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/php/handlers/main.yml