- name: Check if already installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['php-fpm'] | length }} versions of php-fpm are installed!"
  when: "'php-fpm' in ansible_facts.packages"

- name: Update repositories
  ansible.builtin.apt:
    update_cache: yes
  when: "not 'php-fpm' in ansible_facts.packages"

- name: Install the right php-fpm package
  ansible.builtin.package: 
    name: php-fpm=2:8.1+92ubuntu1
  when: "not 'php-fpm' in ansible_facts.packages"

- name: Install the right php-mysql package
  ansible.builtin.package: 
    name: php-mysql=2:8.1+92ubuntu1
  when: "not 'php-mysql' in ansible_facts.packages"

- name: Restart php-fpm
  ansible.builtin.systemd:
    name: php8.1-fpm.service
    state: restarted
  when: "not 'php-fpm' in ansible_facts.packages"

- name: Reload php-fpm
  ansible.builtin.systemd:
    name: php8.1-fpm.service
    state: reloaded