- name: Restart MySQL
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Restart MySQL
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Restart MySQL
  ansible.builtin.service:
    name: mariadb
    enabled: yes