- name: Add the user 'prometheus'
  ansible.builtin.user:
    name: prometheus

- name: Create a directory for prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    recurse: true
    owner: prometheus
    group: prometheus

- name: Check if prometheus is downloaded
  ansible.builtin.shell:
    cmd: "ls /opt/prometheus"
  register: prometheus

- name: Downloading and extracting prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.45.1/prometheus-2.45.1.linux-amd64.tar.gz
    dest: /opt/prometheus/
    remote_src: true
    owner: prometheus
    group: prometheus
    extra_opts: [--strip-components=1]
  when: "prometheus.stdout == ''"

- name: Create daemon for prometheus
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Create config file for prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml

- name: Create rules file for prometheus
  ansible.builtin.template:
    src: prometheus.rules.yml.j2
    dest: /opt/prometheus/prometheus.rules.yml

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/prometheus/handlers/main.yml