- name: Installation of wordpress
  hosts: virtualmachines
  become: true
  gather_facts: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - python3

# Specific modules only       mysql, php, nginx, wordpress, prometheus, fluentd, grafana, nginx_exporter, node_exporter
# Specific distro             ubuntu, amazon
