- name: Add the user 'nginx_exporter'
  ansible.builtin.user:
    name: nginx_exporter

- name: Create a directory for nginx_exporter
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory
    recurse: true
    owner: nginx_exporter
    group: nginx_exporter

- name: Check if nginx_exporter is downloaded
  ansible.builtin.shell:
    cmd: "ls /opt/nginx_exporter"
  register: nginx_exporter

- name: Downloading and extracting nginx_exporter
  ansible.builtin.get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter/
  when: "nginx_exporter.stdout != 'CHANGELOG.md\nLICENSE\nnginx-prometheus-exporter\nREADME.md'"

- name: Check if nginx_exporter_tar is downloaded
  ansible.builtin.shell:
    cmd: "ls /opt/nginx_exporter"
  register: nginx_exporter_tar

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /opt/nginx_exporter/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter/
    remote_src: yes
  when: "nginx_exporter_tar.stdout == 'nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz'"


- name: Remove file .tar
  ansible.builtin.file:
    path: /opt/nginx_exporter/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    state: absent

- name: Create daemon for nginx_exporter
  ansible.builtin.template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/nginx_exporter/handlers/main.yml