- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service node-exporter and ensure it is not masked
  ansible.builtin.systemd:
    name: node-exporter.service
    enabled: true
    masked: no

- name: Reload service node-exporter, in all cases
  ansible.builtin.systemd:
    name: node-exporter.service
    state: reloaded