- name: Install prerequisites
  ansible.builtin.yum: 
    name: yum
    update_cache: yes
    state: latest

- name: Creating nginx.repo
  ansible.builtin.copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: List ansible packages
  ansible.builtin.shell:
    cmd: 'yum list install nginx | cut -d " " -f 1 | head -n 2'
  register: nginx

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    update_cache: yes
    state: latest
  when: "nginx.stdout == 'Loaded\nAvailable'"

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/nginx/handlers/main.yml
