- name: Install prerequisites
  ansible.builtin.yum: 
    name: yum
    update_cache: yes
    state: latest

- name: Creating nginx.repo
  ansible.builtin.copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: List ansible packages
  ansible.builtin.yum:
    list: nginx
  register: nginx

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    update_cache: yes
    state: latest
  when: "nginx.results == ''"

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/nginx/handlers/main.yml
