- name: Check if packages were collected successfully
  ansible.builtin.debug:
    var: ansible_facts.packages['fluent-package']

- name: Set the right timezone
  ansible.builtin.shell: "sudo timedatectl set-timezone Europe/Warsaw"

- name: Override the /etc/security/limits.conf
  ansible.builtin.copy:
    src: limits.conf
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: '0644'

- name: Override the /etc/sysctl.conf
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply changes
  ansible.builtin.shell: "sysctl -p"

# check if the file is there, if not just make ur own file
# there is one more possible file /etc/sysctl.d/10-link-restrictions.conf
# this program dosn't check this file !!!
- name: Check if /usr/lib/sysctl.d/50-default.conf exists
  ansible.builtin.stat:
    path: /usr/lib/sysctl.d/50-default.conf
  register: symlink_protection_file

# Enable hard and soft link protection
- name: Check if 2 lines in /usr/lib/sysctl.d/50-default.conf are present
  ansible.builtin.lineinfile:
    path: /usr/lib/sysctl.d/50-default.conf
    regexp: 'fs\.protected_hardlinks = '
    line: fs.protected_hardlinks = 1
  when: symlink_protection_file.stat.exists

- name: Check if 2 lines in /usr/lib/sysctl.d/50-default.conf are present
  ansible.builtin.lineinfile:
    path: /usr/lib/sysctl.d/50-default.conf
    regexp: 'fs\.protected_symlinks = '
    line: fs.protected_symlinks = 1
  when: symlink_protection_file.stat.exists

- name: Copy a file if /usr/lib/sysctl.d/50-default.conf isn't present
  ansible.builtin.copy:
    src: symlink_protection.conf
    dest: /usr/lib/sysctl.d/symlink_protection.conf
    owner: root
    group: root
    mode: '0644'
  when: not symlink_protection_file.stat.exists


# now we can install Fluentd
- name: Install Fluentd
  ansible.builtin.shell: "curl -fsSL https://toolbelt.treasuredata.com/sh/install-amazon2-fluent-package5-lts.sh | sh"
  when: "ansible_facts.packages['fluent-package'] is undefined"

- name: Add the user 'fluentd' to the group 'adm'
  ansible.builtin.user:
    name: fluentd
    groups: adm
    append: yes

- name: Override the /etc/fluent/fluentd.conf
  ansible.builtin.copy:
    src: fluentd.conf
    dest: /etc/fluent/fluentd.conf
    owner: root
    group: root
    mode: '0644'

# now we add a gem package
- name: Install a gem package
  ansible.builtin.shell: "/opt/fluent/bin/gem install fluent-plugin-prometheus"

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/fluentd/handlers/main.yml