- name: Install build-essential
  ansible.builtin.package:
    name: "build-essential"
  when: "not 'build-essential' in ansible_facts.ohai_packages"

- name: Install ruby
  ansible.builtin.package:
    name: "ruby-dev"
  when: "not 'ruby-dev' in ansible_facts.ohai_packages"

- name: Check if fluentd is installed
  ansible.builtin.shell:
    cmd: "gem list luentd"
  register: fluentd

- name: Install fluentd
  ansible.builtin.shell:
    cmd: "gem install fluentd --no-doc"
  when: "fluentd.stdout == ''"

- name: Check if fluent-plugin is installed
  ansible.builtin.shell:
    cmd: "gem list fluent-plugin-prometheus"
  register: fluent

- name: Install fluentd plugins
  ansible.builtin.shell:
    cmd: "gem install fluent-plugin-prometheus"
  when: "fluent.stdout == ''"

- name: Create a directory for fluentd
  ansible.builtin.file:
    path: /etc/fluent
    state: directory
    owner: nginx
    group: nginx

- name: Create a file for fluentd
  ansible.builtin.file:
    path: /tmp/fluent_nginx.pos
    state: touch
    owner: nginx
    group: nginx

- name: Create config file for fluentd
  ansible.builtin.template:
    src: fluent.conf.j2
    dest: /etc/fluent/fluent.conf

- name: Create daemon for fluentd
  ansible.builtin.template:
    src: fluentd.service.j2
    dest: /etc/systemd/system/fluentd.service

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/fluentd/handlers/main.yml