{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections accepted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_accepted{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Connections handeled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_handled{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "HTTP requests total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Connections writing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{group=\"$node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_up{group=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caught ip addresses [amount of requests all time]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ip_address) (nginx_request_status_code_total{ip_address!~\"\",group=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caught ip addresses [amount of requests]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(ip_address) (nginx_request_status_code_total{ip_address!~\"\",group=\"$node\"})",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Sum of status codes",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (nginx_request_status_code_total{ip_address!~\"\",group=\"$node\"})",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Paths that returned 404 [all time]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_request_status_code_total{status_code=\"404\",group=\"$node\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Disk Space in use [%]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{mountpoint=\"/\",group=\"$node\"}) / 1000000000) / (sum(node_filesystem_size_bytes{mountpoint=\"/\",group=\"$node\"}) / 1000000000))*100",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",group=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage [%]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",group=\"$node\"}[10m])) by (instance)) * 100",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Number of cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{group=\"$node\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage [%]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{group=\"$node\"}[10m]) + avg_over_time(node_memory_Cached_bytes{group=\"$node\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{group=\"$node\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{group=\"$node\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{group=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime [h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{group=\"$node\"} ) / 3600",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}