{
 "title": "Specs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_memory_MemTotal_bytes",
    "label": "node_memory_MemTotal_bytes",
    "query": {
     "query": "query_result(node_memory_MemTotal_bytes)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds)/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 13, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "In use memory"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Free memory" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory usage on graph",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Free memory" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory in use"
    }
   ]
  },
  {
   "title": "CPU usage on graph",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}