{
 "title": "Wordpress info",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "Power status ( {{group}} )" }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (nginx_request_status_code_total{ip_address!=\"127.0.0.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections from specific countries",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(geoCountry) (nginx_request_status_code_total{geoCountry!~\"-|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "description": "Total - 1 = all active users",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active users on {{group}}" }
   ]
  },
  {
   "title": "Paths with not success status code",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code, path, ip_address) (nginx_request_status_code_total{status_code!=\"200\"})",
     "legendFormat": "{{ip_address}}{{path}} code {{status_code}}"
    }
   ]
  },
  {
   "title": "Connections from hosts",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 11, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ip_address, group) (nginx_request_status_code_total{ip_address!=\"127.0.0.1\"})",
     "legendFormat": "{{ip_address}} on {{group}}"
    }
   ]
  },
  {
   "title": "Visited sites",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum by(path, ip_address) (nginx_request_status_code_total{path!~\"/status\"})",
     "legendFormat": "{{ip_address}}{{path}}"
    }
   ]
  }
 ]
}