# ip addresses (for ansible)
#
# if more ip addresses/machines are added, they should be added to: (for bakcup on amazonLinux)
#  - roles -> backup -> templates -> hosts.allow.j2
amazon_ip: "192.168.50.100"

# MySQL Settings
mysql_root_password: "1234"
mysql_db: "wordpress" # DO NOT change
mysql_user: "wordpressuser"
mysql_password: "1234"
mysql_db_prefix: wp_


# Wordpress Settings
# wp_url: ""                          # These addresses are used not only in WP,
wp_url1: "www.mikolaj.dev.zdt.io"     # the config of prometheus/nginx also depends on it (be carefull when changing it)              
wp_title1: "mikolaj.com"              # and make sure if they are domain names that they can be seen from the internet
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"

# Certbot
certbot_domain_list: [www.mikolaj.dev.zdt.io, mikolaj.dev.zdt.io]

# Grafana for Ubuntu
ubuntu_grafana_url: "http://192.168.50.103:3000"
grafana_user: "admin"
grafana_password: "admin"
org_id: "1"
ds_name: "Prometheus"
ds_type: "prometheus"
ds_url: "http://localhost:9090"

# Granfana for AmazonLinux
amazon_grafana_url: "http://192.168.50.102:3000"
amazon_grafana_user: "admin"
amazon_grafana_password: "admin"
amazon_org_id: "1"
amazon_ds_name: "Prometheus"
amazon_ds_type: "prometheus"
amazon_ds_url: "http://localhost:9090"


backups_address: "192.168.50.105"
backups_username: "backups"
backups_password_hashed: "$6$uUU.qnsvw2Dn.tal$l5pD6SozfYfK9DQGqgZDKxX57T.v5De1T4HXUjyPAF6iPYXjzqEAKap0R8amJ9Kg4QWwfwUWeiN7SBGfEcZ111"
backups_password: "123"

# backup config
backup_app_root: "/etc/backupAmazon"
backup_server_ip: "192.168.50.105"
backup_user: "backups" # this will create a system user on the backup server
backup_password: "1234"
backup_hashed_password: "$6$vr/4bYgE.AMhe24Z$BVzlmeOAvGaI376SML.xVrwXbfVSWe2ZF0kZSw1fD6FAysDUuJ3WuIHzPNfdWjncIK5ZyEI4fkf5H1rdIctDF0"
#
# !!! important, if you change password for user backup (^), 
# you will have to generate it's hashed version and insert it above
#