# MySQL Settings
mysql_root_password: "1234"
mysql_db: "wordpress" # DO NOT change
mysql_user: "wordpressuser"
mysql_password: "1234"
mysql_db_prefix: wp_


# Wordpress Settings
wp_url: "www.pawel.dev.zdt.io"      # These addresses are used not only in WP,
wp_url_no_www: "pawel.dev.zdt.io"
wp_title: "amazon.LIVE.pawel.com"        # and make sure if they are domain names that they can be seen from the internet
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"