#MySQL Settings
mysql_root_password: "zaq1@WSXcde3$RFV"
mysql_db: "wordpress"
mysql_user: "wordpressuser"
mysql_password: "123"
mysql_db_prefix: wp_


#Wordpress Settings
wp_url: "192.168.50.100"
wp_url1: "192.168.50.101"
wp_title: "amazon.com"
wp_title1: "ubuntu.com"
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"


ubuntu_grafana_url: "http://192.168.50.103:3000"
grafana_user: "admin"
grafana_password: "admin"
org_id: "1"
ds_name: "Prometheus"
ds_type: "prometheus"
ds_url: "http://localhost:9090"
