#MySQL Settings
mysql_root_password: "zaq1@WSXcde3$RFV"
mysql_db: "wordpress"
mysql_user: "wordpressuser"
mysql_password: "123"
mysql_db_prefix: wp_


#Wordpress Settings
wp_url: "192.168.50.100"
wp_url1: "192.168.50.101"
wp_title: "amazon.com"
wp_title1: "ubuntu.com"
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"

# Granfana for AmazonLinux
amazon_grafana_url: "http://192.168.50.102:3000"
amazon_grafana_user: "admin"
amazon_grafana_password: "admin"
amazon_org_id: "1"
amazon_ds_name: "Prometheus"
amazon_ds_type: "prometheus"
amazon_ds_url: "http://localhost:9090"