# MySQL Settings
mysql_root_password: "1234"
mysql_db: "wordpress" # DO NOT change
mysql_user: "wordpressuser"
mysql_password: "1234"
mysql_db_prefix: wp_

# Wordpress Settings
# wp_url: ""                          # These addresses are used not only in WP,
wp_url1: "www.mikolaj.dev.zdt.io"     # the config of prometheus/nginx also depends on it (be carefull when changing it)              
wp_title1: "eeeeeeeeeee"              # and make sure if they are domain names that they can be seen from the internet
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"

# Certbot
certbot_domain_list: [www.mikolaj.dev.zdt.io, mikolaj.dev.zdt.io]