# MySQL Settings
mysql_root_password: "1234"
mysql_db: "wordpress"
mysql_user: "wordpressuser"
mysql_password: "123"
mysql_db_prefix: wp_


# Wordpress Settings
wp_url: "192.168.50.100"      # These addresses are used not only in WP,
wp_url1: "192.168.50.101"     # the config of prometheus also depends on it (be carefull when changing it)
wp_title: "amazon.com"
wp_title1: "ubuntu.com"
wp_admin: "admin"
wp_password: "1234"
wp_email: "zrobione.com@zdt.io"

# Grafana for Ubuntu
ubuntu_grafana_url: "http://192.168.50.103:3000"
grafana_user: "admin"
grafana_password: "admin"
org_id: "1"
ds_name: "Prometheus"
ds_type: "prometheus"
ds_url: "http://localhost:9090"

# Granfana for AmazonLinux
amazon_grafana_url: "http://192.168.50.102:3000"
amazon_grafana_user: "admin"
amazon_grafana_password: "admin"
amazon_org_id: "1"
amazon_ds_name: "Prometheus"
amazon_ds_type: "prometheus"
amazon_ds_url: "http://localhost:9090"
