- name: just checking
  ansible.builtin.debug:
    msg: "it is working for ubuntuProm"

# - name: Install something for grafana
#   ansible.builtin.apt:
#     name: 'adduser libfontconfig1 musl'
#     state: present

- name: Create a directory for grafana
  ansible.builtin.file:
    path: /opt/grafana
    state: directory
    recurse: true
  tags: [ Grafana ]

- name: Downloading grafana
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.2.0_amd64.deb
    dest: /opt/grafana/
  tags: [ Grafana ]


- name: Install grafana
  ansible.builtin.apt:
    deb: /opt/grafana/grafana_10.2.0_amd64.deb
    
- name: Recursively remove directory
  ansible.builtin.file:
    path: /opt/grafana
    state: absent

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/grafana/handlers/main.yml
  tags: [ System, Prometheus ]

#                                                                       GRAFANA
# sudo apt-get install -y adduser libfontconfig1 musl &&
# wget https://dl.grafana.com/oss/release/grafana_10.2.0_amd64.deb &&
# sudo dpkg -i grafana_10.2.0_amd64.deb                                                                    

# albo

# sudo apt-get install grafana

# sudo systemctl start grafana-server &&
# sudo systemctl enable grafana-server