- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service prometheus and ensure it is not masked
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    masked: no

- name: Reload service prometheus, in all cases
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded