- name: Installation of wordpress

  hosts: virtualmachines
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
  roles:
    - mysql
    - nginx
    - php
    - wordpress

- name: Installation of prometheus

  hosts: observators
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
  roles:
    - prometheus

# Specific modules only       MySQL, PHP, Nginx, Wordpress
# System installation         System
