- name: Installation of wordpress
  hosts: cloud
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  pre_tasks:
    - name: Setting the package manager to auto
      package_facts:
        manager: "auto"
      tags: [always]
  roles:
    - debug
    - mysql
    - nginx
    - php
    - wordpress
    - ssl_cert

# Specific modules only       mysql, php, nginx, wordpress, prometheus, fluentd, grafana, nginx_exporter, node_exporter
# Specific distro             ubuntu, amazon
