- name: Installation of wordpress

  hosts: virtualmachines
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - mysql
    - nginx
    - php
    - wordpress
    - node_exporter
    - nginx_exporter
    - fluentd

- name: Installation of prometheus

  hosts: observators
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - prometheus
    - grafana

# Specific modules only       mysql, php, nginx, wordpress, prometheus, fluentd, grafana, nginx_exporter, node_exporter
# Specific distro             ubuntu, amazon
