- name: Check if wokrs properly
  ansible.builtin.debug:
    msg: ubuntuBack is ready!

# // in ansible
# # yum install mysql

# // in cron
# # 
# # mysqldump --host=192.168.50.100 --user=root --port=3306 --password=1234 wp_wpdb > 

