- name: Create folders for scripts
  ansible.builtin.file:
    path: /scripts
    state: directory

- name: Create folders for backups
  ansible.builtin.file:
    path: /backupsUbuntu
    state: directory

- name: Copy all scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /scripts
    mode: +x
  loop: [ ftp.bash, cronFoldersYear.bash, cronFoldersMonth.bash, cronFoldersWeek.bash, variables ]

- name: Copy all scripts
  ansible.builtin.template:
    src: cronFOM.bash.j2
    dest: /scripts/ronFOM.bash
    mode: +x

- name: Copy all scripts
  ansible.builtin.template:
    src: cronWeekly.bash.j2
    dest: /scripts/cronWeekly.bash
    mode: +x

- name: Copy all scripts
  ansible.builtin.template:
    src: cronWeeklyFull.bash.j2
    dest: /scripts/cronWeeklyFull.bash
    mode: +x

- name: Copy all scripts
  ansible.builtin.template:
    src: cronRestore.bash.j2
    dest: /scripts/cronRestore.bash
    mode: +x

- name: Create folders for backups (year)
  ansible.builtin.shell:
    cmd: bash /scripts/cronFoldersYear.bash
  
- name: Create folders for backups (month)
  ansible.builtin.shell:
    cmd: bash /scripts/cronFoldersMonth.bash

- name: Create folders for backups (week)
  ansible.builtin.shell:
    cmd: bash /scripts/cronFoldersWeek.bash

- name: Overrite mysql conf
  ansible.builtin.copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Create crontab jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    month: "{{ item.month }}"
    weekday: "{{ item.weekday }}"
    user: root
    job: "{{ item.job }}"
  loop:
    - { job: 'bash /scripts/cronFoldersYear.bash',  name: 'Years', minute: '0', hour: '19', day: '1', month: '1', weekday: '*' }
    - { job: 'bash /scripts/cronFoldersMonth.bash', name: 'Months', minute: '1', hour: '19', day: '1', month: '*' , weekday: '*' }
    - { job: 'bash /scripts/cronFoldersWeek.bash',  name: 'Weekends', minute: '2', hour: '19', day: '*', month: '1', weekday: 'Sun' }
    - { job: 'bash /scripts/cronFOM.bash',          name: 'FOM', minute: '0', hour: '20', day: '1', month: '*' , weekday: '*' }
    - { job: 'bash /scripts/cronWeeklyFull.bash',   name: 'WeeklyFull', minute: '1', hour: '20', day: '1', month: '*' , weekday: 'Sun' }
    - { job: 'bash /scripts/cronWeekly.bash',       name: 'WeeklyMon', minute: '2', hour: '20', day: '*', month: '*' , weekday: '1' }
    - { job: 'bash /scripts/cronWeekly.bash',       name: 'WeeklyWed', minute: '3', hour: '20', day: '*', month: '*' , weekday: '3' }
    - { job: 'bash /scripts/cronWeekly.bash',       name: 'WeeklyFri', minute: '4', hour: '20', day: '*', month: '*' , weekday: '5' }

- name: Restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted