- name: Install prerequisites
  ansible.builtin.yum: 
    name: yum
    update_cache: yes
    state: latest

- name: List ansible packages
  ansible.builtin.shell:
    cmd: "yum list installed | grep mariadb-server"
  register: mariadb

- name: sdnjfnd
  ansible.builtin.debug:
    var: mariadb

- name: Install mariaDB
  ansible.builtin.yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: [ 'mariadb-server-5.5.68', 'mariadb-5.5.68' ]
  when: "mariadb.stdout == ''"

- name: List ansible packages
  ansible.builtin.yum:
    list: python3
  register: python3

- name: Install python3-pip
  ansible.builtin.yum:
    name: python3-pip-20.2.2 
    update_cache: yes
    state: latest
  when: "python3.results == ''"

- name: List ansible packages
  ansible.builtin.yum:
    list: pexpect
  register: pexpect

- name: Install pexpect
  ansible.builtin.shell:
    cmd: python3 -m pip install pexpect
  when: "pexpect.results == ''"

- name: List ansible packages
  ansible.builtin.yum:
    list: PyMySQL
  register: PyMySQL

- name: Install PyMySQL
  ansible.builtin.shell:
    cmd: python3 -m pip install PyMySQL==1.1.0
  when: "PyMySQL.results == ''"

- name: Start mysql
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Waits for port 3306 (mysql)
  ansible.builtin.wait_for:
    port: 3306
    delay: 8
    state: started

- name: secure mariadb
  become: yes
  ansible.builtin.expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Set root password': 'y'
      'New password': '{{ mysql_root_password }}'
      'Re-enter new password': '{{ mysql_root_password }}'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database': 'y'
      'Reload privilege tables now': 'y'
    timeout: 1
    echo: yes
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb"
  
- name: Creates database for WordPress
  ansible.builtin.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  ansible.builtin.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/mysql/handlers/main.yml