- name: Check if packages were collected successfully
  ansible.builtin.debug:
    var: ansible_facts.packages['mariadb105']

- name: Update repositories
  ansible.builtin.dnf: 
    name: dnf
    update_cache: yes
    state: latest

- name: Install mariaDB
  ansible.builtin.dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: [ 'mariadb105-server', 'mariadb105' ]
  when: "ansible_facts.packages.mariadb105 is undefined"

- name: Install python3-pip
  ansible.builtin.dnf:
    name: python3-pip
    update_cache: yes
    state: latest

- name: Install pexpect
  ansible.builtin.shell:
    cmd: python3 -m pip install pexpect

- name: Install PyMySQL
  ansible.builtin.shell:
    cmd: python3 -m pip install PyMySQL

- name: Start mariadb
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Waits for port 3306 (mysql)
  ansible.builtin.wait_for:
    port: 3306
    delay: 8
    state: started

- name: secure mariadb
  become: yes
  ansible.builtin.expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Switch to unix_socket authentication': 'n'
      'Change the root password?': 'y'
      'Set root password': 'y'
      'New password': '{{ mysql_root_password }}'
      'Re-enter new password': '{{ mysql_root_password }}'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database': 'y'
      'Reload privilege tables now': 'y'
    timeout: 1
    echo: yes
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb"
  when: "ansible_facts.packages.mariadb105 is undefined"
  
- name: Creates database for WordPress
  ansible.builtin.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: "ansible_facts.packages.mariadb105 is undefined"

- name: Create MySQL user for WordPress
  ansible.builtin.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: "ansible_facts.packages.mariadb105 is undefined"

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/mysql/handlers/main.yml