# this 
# https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_selfsigned.html

- name: Create a directory /etc/ssl/private
  ansible.builtin.file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create a directory /etc/nginx/snippets
  ansible.builtin.file:
    path: /etc/nginx/snippets
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install cryptography python package
  ansible.builtin.pip:
    name: cryptography

- name: Generate an OpenSSL private key with a different size (2048 bits)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/nginx_selfsigned.key
    size: 2048

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/nginx_selfsigned.crt
    privatekey_path: /etc/ssl/private/nginx_selfsigned.key
    provider: selfsigned

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: /etc/ssl/dhparams.pem
    size: 2048

- name: Copy /etc/nginx/snippets/self-signed.conf
  ansible.builtin.template:
    src: self-signed.conf.j2
    dest: /etc/nginx/snippets/self-signed.conf

- name: Copy /etc/nginx/conf.d/default.conf
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Copy ssl-params.conf
  ansible.builtin.copy:
    src: ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
    owner: root
    group: root
    mode: 0644

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/ssl_cert/handlers/main.yml


# or prompt answers: 
# in shell:
# 
# mkdir -p /etc/ssl/private
# 
# sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
# 
# Country Name (2 letter code) [XX]:PL
# State or Province Name (full name) []:Małopolska
# Locality Name (eg, city) [Default City]:Kraków
# Organization Name (eg, company) [Default Company Ltd]:wordpress.inc
# Organizational Unit Name (eg, section) []:Ministry of stuff
# Common Name (eg, your name or your server's hostname) []:wordpress.inc.com.net
# Email Address []:stuff@wp.com
# 
# sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 (a long process)
# 
# mkdir /etc/nginx/snippets
# 
# *** copy the file /etc/nginx/snippets/self-signed.conf ***
# 
# *** copy the file /etc/nginx/snippets/ssl-params.conf ***
# 
# *** edit the file default.conf (where it was previously modified AS A TEMPLATE) ***
# 
# restart nginx
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
