# LET'S ENCRYPT CONFIG

- name: Install prerequisites
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop: [python3, python3-venv, libaugeas0]

- name: Create a venv
  ansible.builtin.shell: "python3 -m venv /opt/certbot/"

- name: Update pip in venv
  ansible.builtin.shell: "/opt/certbot/bin/pip install --upgrade pip"

- name: Install certbot in venv with pip
  ansible.builtin.shell: "/opt/certbot/bin/pip install certbot certbot-nginx"

- name: Make a symlink / start certbot at start
  ansible.builtin.shell: "ln -s /opt/certbot/bin/certbot /usr/bin/certbot"

# now we create a certificate

- name: Generate a cert for each domain separately
  ansible.builtin.shell: certbot --nginx --non-interactive --agree-tos -m mikolaj.zasko890290@google.com -d "{{item}}"
  loop: "{{certbot_domain_list}}"

- name: Add a daily cron job
  ansible.builtin.cron:
    name: "Daily renewal check"
    minute: "1"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    job: "cd / ; certbot renew --quiet"
    user: root

- name: Restart cron service
  ansible.builtin.systemd:
    state: restarted
    name: cron
