- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service node_exporter and ensure it is not masked
  ansible.builtin.systemd:
    name: node_exporter.service
    enabled: true
    masked: no

- name: Reload service node_exporter, in all cases
  ansible.builtin.systemd:
    name: node_exporter.service
    state: restarted